### PR TITLE
build: added pyproject.toml

### PR DESCRIPTION
**Pull request by teto**
The 'setup.py' approach is hardly automatable, which is why the python ecosystem currently discourage it peps.python.org/pep-0518 . The pyproject.toml can be parsed by 3rd-party tools while addressing shortcomings of setup.py (can create a sandbox a la pipenv).

`poetry install`

### CODE REVIEW

**Comment by pazz** [comment]
nice, cheers!
Would you mind updating the docs also?

**Comment by teto** [comment]
sure, do you mean the "contributing" section about running tests ? any other places you have in mind
what about the setup.py ? shall it be kept during the transition to smooth things out ( I think so) ?

**Comment by pazz** [comment]
I thought there was already some part in the docs where we mention pip, but I cannot find it now.
Was thinking of here https://alot.readthedocs.io/en/latest/installation.html

Just wanted to make sure that all suggestions for installation paths are in the same place..
Cheers!
P

Quoting Matthieu Coudron (2023-05-22 10:02:47)

**Comment by teto** [comment]
I haven't updated the instructions to generate the documentation since `poetry run make -C docs html` is kinda different than the current approach. Let me know if it's ok to add sphinx as a dev dependency else I will remove the last commit

**Comment by teto** [comment]
thank you sorry I was not sure how to answer. If you have trouble with the recent merge let me know and I'll try to address the issues.

**Comment by pazz** [comment]
No worries, and thanks for the PR.
Do you have an opinion about how to deal with the bot-suggested version
bumps? Can we simply allow them in? It looks alright to me..
P

Quoting Matthieu Coudron (2023-07-26 14:15:13)

**Comment by teto** [comment]
> Do you have an opinion about how to deal with the bot-suggested version
bumps? Can we simply allow them in? It looks alright to me..

which one ?

**Comment by teto** [comment]
ha this https://github.com/pazz/alot/pull/1623 ? probably fine

**Comment by pazz** [comment]
Quoting Matthieu Coudron (2023-07-28 12:46:15)

> ha this #1623 ? probably fine

Yes thanks.
More generally I have not seen these automatic PRs before and wanted your take on them.
Thx

**Comment by teto** [comment]
This PR didnt change the settings so it must have preexisted. Feel free to disable dependabot in gitlab settings. We can accept those automated PRs only if we are confident in the testuite

**Pull request merged**
