### PR TITLE
alot/completion: revert premature optimization

### LINKED ISSUE #962: envelope: set command removed by auto-complete
Steps to reproduce:
Start new mail, save, press `c` to add Cc, start typing an email, press `tab`. The name and email will be completed, but the `Cc` will be removed.

### PR DESCRIPTION
**Pull request by dcbaker**
The change this is partially reverting removed a variable assignment
that was actually needed.

Fixes #962

### CODE REVIEW

**Comment by pazz** [comment]
just tested this and there is another (related?) problem:

do what you did, hit `c` to get a prompt for Cc but then hit escape to cancel.
I get the following printed on screen:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1241, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.4.dev0-py2.7.egg/alot/commands/globals.py", line 147, in apply
    raise CommandCanceled()

```

**Comment by pazz** [comment]
this happens on master as well btw.

**Comment by dcbaker** [comment]
I looked into it, and I can replicate that all the way back to 3.6 (the compose option changed to it's current semantics in 3.6), so while it's definately related I don't think it's the same bug or introduced at the same time. If you can verify that my findings are correct we should open a different bug for that.

**Comment by pazz** [comment]
thanks, please do that. I'll merge this here

**Pull request merged**
