### PR TITLE
Some minor style fixes/improvements

### PR DESCRIPTION
**Pull request by lucc**
Just stuff that was reported by flake8, pycodechecker, pylint, and friends.

It should also be possible to cherry-pick individual commits if you prefer.

If I have some more time I will also push some commits with docstrings to this branch.

### CODE REVIEW

**Comment by pazz** [comment]
quick question regarding relative imports etc: will this be compatible with py3k afterwards? because i vaguely remember some patches regarding imports that aimed at py3k compatibility

**Comment by lucc** [comment]
A quick check:
```sh
git co minor
2to3 alot 2>/dev/null|grep '[+-].*import'
```
returns 
```
-from cStringIO import StringIO
+from io import StringIO
-from cStringIO import StringIO
+from io import StringIO
-        import urllib
+        import urllib.request, urllib.parse, urllib.error
+import collections
-from StringIO import StringIO
+from io import StringIO
+import collections
-from cStringIO import StringIO
+from io import StringIO
+import collections
+import collections
+import collections
-from cStringIO import StringIO
+from io import StringIO
-from urlparse import urlparse
+from urllib.parse import urlparse
```
which looks like normal conversions that are necessary for py3 anyways. My conclusion: This should be compatible with py3.

**Comment by lucc** [comment]
As it was problematic to merge these big py3 PRs in the past we might think about doing the py3 conversion incrementally. 
* imports as far as possible (like here)
* print function (with `from __future__ import print_function`)
* I don't know what

**Comment by pazz** [comment]
sorry for introducing these conflicts. I merged a bunch of other PRs in order to flush out a release soon..
If you find the time to rebase soon, I'd push these as well.

**Comment by lucc** [comment]
sorry for being late for the release. Please have a look at the changes again to ensure I did not introduce a mistake when rebasing (I didn't find one).

**Comment by pazz** [comment]
no worries, we can fire out another release any time :)

**Comment by pazz** [comment]
would you like the honour of pushing it yourself? :P

**Comment by lucc** [comment]
Thanks for the honor :)

**Pull request merged**
