### PR TITLE
Fix editnew error where account might be None in ComposeCommand

### LINKED ISSUE #819: editnew bug
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/ui.py", line 633, in call_apply
    return defer.maybeDeferred(cmd.apply, self)ts
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result) is already due since 23 Dec 2015.
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/commands/globals.py", line 846, in apply
    if self.encrypt or account.encrypt_by_default:
exceptions.AttributeError: 'NoneType' object has no attribute 'encrypt_by_default'

```

### PR DESCRIPTION
**Pull request by meskio**
Fixes #819.

### CODE REVIEW

**Comment by pazz** [comment]
how could `account` possibly be None?

**Comment by pazz** [comment]
aha! https://github.com/pazz/alot/blob/master/alot/commands/globals.py#L798

Since subsequently, many of these checks if `account` is not None occur, I supose it'd be best if
this line was replaced with something that ensures that this is the case, for instance by defaulting to
the first account or so. This would make perfect sense for this command i think.

**Comment by meskio** [comment]
I agree, it's a good idea to default to an account. Let's try to fix it this way.

**Comment by meskio** [comment]
I force-pushed the fix by setting the first configured account if no address matches.

**Comment by pazz** [comment]
It seems that from line 749 onwards we already determine the account to be used.
I think just before this point, the account should be determined, by looking up the From-header if exists, and by prompting otherwise, and if no accounts are set up we can raise an exception.
From that point onwards we can then safely use the `account` variable.

**Comment by meskio** [comment]
In line 749 it determine the From, I just moved the account set below that, you are right that it makes sense to do it there.

**Comment by meskio** [comment]
bump as requested in #819

**Comment by pazz** [comment]
pushed to testing. thanks and sorry for the delay

**Pull request merged**
