### PR TITLE
travis: Use github mirror of notmuch source

### PR DESCRIPTION
**Pull request by dcbaker**
Since the git repo on notmuchmail.org seems to be down.

### CODE REVIEW

**Comment by pazz** [comment]
are we sure that this repo is regularly synced? In that case, sure.

**Comment by dcbaker** [comment]
We're not. I'ts 7 days out of date right now, but since neither I nor the CI can clone from notmuchmail.org we need to do something, and this seemed like the most expedient fix. Maybe a better solution would be to skip using git at all and just uses the most recent tarball?

**Comment by pazz** [comment]
Actually, I think you are right and we should use the latest stable release: alot master should work seamlessly with that and  this way we're less afflicted by a buggy development version 
(which I consider rather unlikely) or notmuchmail.org hiccups, which do happen from time to time..

**Comment by dcbaker** [comment]
Okay, I'll do that instead.

**Pull request closed without merging**
