### PR TITLE
Use db.utils.formataddr instead of email.utils.formataddr

### PR DESCRIPTION
**Pull request by Tyilo**
This should fix the problem described in #1388

### CODE REVIEW

**Comment by pazz** [comment]
We need to double check the tests. See also
https://github.com/pazz/alot/commit/d916b5e42ffd6b5128333321d68365744ca08b1d
for the tests I wrote for the formataddr method.

In the long run, I'm *really* looking forward to using the new python3 email API, which seems to deal much better with encoding issues.

**Comment by teto** [comment]
> In the long run, I'm really looking forward to using the new python3 email API, which seems to deal much better with encoding issues.

what's preventing it ? time ?

**Comment by pazz** [comment]
yes, mostly.

I have no idea yet how to combine the new email API (search for email.message.EmailMessage), which abstracts from manual MIMEMessage building, with pgp/mime. Ideally, someone would write a module that we could use to construct S/MIME or PGP/MIME messages from these EmailMessages. This *could* be easy, but I have not done any research on it.

It should be fairly easy to switch to the new API and break the crypto features in alot, but I assume this will be unpopular. :)

**Comment by teto** [comment]
(sry I removed my post when I saw your topic https://github.com/pazz/alot/issues/1409 :) )

**Comment by pazz** [comment]
can we close this? the issue #1388 is closed already..

**Comment by Tyilo** [comment]
Sure

**Pull request closed without merging**
