### PR TITLE
Indicate untrusted PGP signatures in thread view.

### PR DESCRIPTION
**Pull request by lucc**
This was originally proposed in #849.  This PR still shares commits (all but f87257d) with #854 so it should be merged after that (and maybe also rebased after #854 is merged).

### CODE REVIEW

**Comment by pazz** [comment]
pushed to `0.3.8-feature-untrusted-signatures-858` (needs rebase to master after `0.3.8-settings-encrypt-by-default-854` is pushed!).
I also pushed both series to `testing`.

**Comment by pazz** [comment]
i believe this is related:?

```
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/commands/search.py", line 38, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/buffers.py", line 334, in __init__
    self.rebuild()
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/buffers.py", line 362, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/widgets/thread.py", line 357, in __init__
    accumulate(msg)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/widgets/thread.py", line 336, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/widgets/thread.py", line 169, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/widgets/thread.py", line 196, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/widgets/thread.py", line 259, in _get_headers
    headers)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/widgets/thread.py", line 273, in construct_header_pile
    mail = self._message.get_email()
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/db/message.py", line 74, in get_email
    self._email = message_from_file(f_mail)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/db/utils.py", line 143, in message_from_file
    add_signature_headers(m, sigs, malformed)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.8.dev0-py2.7.egg/alot/db/utils.py", line 68, in add_signature_headers
    if uid_trusted else
exceptions.UnboundLocalError: local variable 'uid_trusted' referenced before assignment


```

**Comment by lucc** [comment]
Does d860722 fix it?

**Comment by pazz** [comment]
Yes, thanks!

**Comment by pazz** [comment]
pushed to master

**Pull request closed without merging**
