### PR TITLE
Use print function from `__future__`

### PR DESCRIPTION
**Pull request by lucc**
Related #969, #779, #800
label: py3k

### CODE REVIEW

**Comment by pazz** [comment]
This looks totally harmless to me. The file `extra/tagsections_convert.py ` can actually be removed completely: it was a converter script for users of an earlier version with incompatible config format.
I think it's safe to assume that this will never be used anymore.

The other stuff is in the docstrings only, and I'm ok with making this change for consistency with further py3k ports.

regarding putting `__future__` import everywhere: OK, but I think it only makes sense in those places where we actually use those imports. I'd like to avoid imporing all kinds of unused stuff.

**Comment by lucc** [comment]
So if I see that correctly we don't use print in any real code any more. Only in this one doctest.  Hence I vote that we drop this PR and the print_function import and port *all* doctest to unittests instead.

**Comment by pazz** [comment]
fine with me

**Comment by lucc** [comment]
@pazz and what about the file extra/theme_convert.py?

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2017-01-17 12:16:56)
>    [1]@pazz and what about the file extra/theme_convert.py?

Same thing. I forgot to mention that, thx.

**Comment by lucc** [comment]
I withdraw this PR in favor of #975.

**Pull request closed without merging**
