### PR TITLE
RFE: implement folder tree buffer

### PR DESCRIPTION
**Pull request by TomasTomecek**
Related to #331 
## Contains
- discover maildir structure
- query notmuch for # of unread msgs in folders
- display as tree
- theming:
  - empty folders
  - not empty folders
  - focused folders
- configuration
  - path to maildir
  - blacklisted folders
- enable (un)folding
- implement refresh
## Bugs

(these should be addressed **before** merging)
- [x] ~~collapse/expand all doesn't work~~ (IMO doesn't make much sense)
- [x] function next/previous unread folder behaves oddly on subfolders
- [x] get rid of TODOs and FIXMEs from the patch
- [x] docs
  - [x] written docs
  - [x] docstrings
## RFEs

(these may be addressed in subsequent PRs)
- completion for folders when searching
- new command: pre-complete searching for selected folder
- figure out something better for status line of folders buffer (e.g. # of new messages in favorite folders)

### CODE REVIEW

**Comment by TomasTomecek** [comment]
@pazz could I get some feedback here?

Would be awesome to have this merged so I don't have to run alot from my custom branch.

**Comment by pazz** [comment]
the biggest problem i have with this is that its difficult to review because its one large commit.
Also, I wonder if we cannot get rid of this extra os.walk replacement and rather use the standard lib somehow. it will be difficult to support this when the stdlib changes.
The way the tree looks should be configurable (thx for amending the theme files btw)

**Comment by TomasTomecek** [comment]
> the biggest problem i have with this is that its difficult to review because its one large commit.

I could probably break it a bit. The thing is that most basic implementation will have several hundreds lines of code anyway.

> Also, I wonder if we cannot get rid of this extra os.walk replacement and rather use the standard lib somehow. it will be difficult to support this when the stdlib changes.

The custom walk replacement solves this issue:

https://www.python.org/dev/peps/pep-0471/

**Comment by pazz** [comment]
about the custom walks and path explorations:
I think there is a much nicer solution which is to let the notmuch database provide the visible folders.
You can define for instance a new `Tree` subclass (that you later display) that gets its information from
notmuch:

```python
db=notmuch.Database()
notmuch_path  = db.get_path()
root = db.get_directory(notmuch_path)  # this is a notmuch.Directory
children = root.get_child_directories
```

You can for instance preproces this, instanciating a `SimpleTree`... no os.path voodoo needed.

**Comment by TomasTomecek** [comment]
Oh my... When I wrote this back then, that api of notmuch wasn't available yet. It will make the code _way_ more simple. Will rebase and rewrite (it will take a couple of weeks since I'm pretty busy lately).

**Comment by pazz** [comment]
Quoting Tomas Tomecek (2015-11-04 11:59:53)
>    Oh my... When I wrote this back then, that api of notmuch wasn't available
>    yet. It will make the code way more simple. Will rebase and rewrite (it
>    will take a couple of weeks since I'm pretty busy lately).

no problem, take your time :)

**Comment by TomasTomecek** [comment]
Rewritten (using notmuch folder api) and rebased against master. Removed also the blacklist folder functionality.

**Comment by pazz** [comment]
looks good at first glance. please split this into separate patches, even if the functionality only makes sense as a whole.

**Comment by TomasTomecek** [comment]
hope I'll manage to do this around Christmas

**Comment by TomasTomecek** [comment]
rebased against testing (can't change base branch of this PR, that's why your commit is in there), updated docstrings and some code a tiny bit, split into multiple commits (not sure about the granularity)

let me know if this is fine

**Comment by pazz** [comment]
I don't understand why you have a class "Account": notmuch has no concept of accounts and
as far as i understand, this new buffer type allows to list those folders seen and indexed by notmuch.
So you should not need this. Also, please check but i think libnotmuch already has a class "Folder". why do you need another wrapper?

**Comment by TomasTomecek** [comment]
> I don't understand why you have a class "Account": notmuch has no concept of accounts and
> as far as i understand, this new buffer type allows to list those folders seen and indexed by notmuch.
> So you should not need this.

We can rename it. Would `Folders` be fine?

> Also, please check but i think libnotmuch already has a class "Folder". why do you need another wrapper?

There's just `Filename` and `Directory` and those contain filesystem related methods, not stuff for doing queries.

https://notmuch.readthedocs.org/en/0.15/filesystem.html

The wrapper of mine is responsible for doing `unread` queries, e.g.:

```
$ notmuch count folder:"Inbox" tag:unread
```

**Comment by TomasTomecek** [comment]
Updated (please, don't get scared by the number of commits, will squash in the end -- I think that squashing it now would make the review process more complicated).

**Comment by ibotty** [comment]
Any news?

**Comment by TomasTomecek** [comment]
I am using this ever since I wrote it and it works just fine.

**Comment by mschaaf** [comment]
@TomasTomecek are still working on your pull request? I will like to use it but with the current master branch.

**Comment by TomasTomecek** [comment]
@mschaaf I'm not working on it any more, hence closing

**Pull request closed without merging**
