### PR TITLE
periodic-hook async

### PR DESCRIPTION
**Pull request by gauteh**
…lar style as call)

### CODE REVIEW

**Comment by pazz** [comment]
sure, but what is the use case? I usually try to avoid adding such "features" just for the sake of it because the code base is already quite bloated...

**Comment by gauteh** [comment]
I was trying to set up a way to sync mail with responsive UI that still could update the UI when done:

```
async def run(cmd):
  import logging
  import asyncio

  proc = await asyncio.create_subprocess_shell(
      cmd,
      stdout=asyncio.subprocess.PIPE,
      stderr=asyncio.subprocess.PIPE)

  stdout, stderr = await proc.communicate()

  logging.debug(f'[{cmd!r} exited with {proc.returncode}]')
  if stdout:
    logging.debug(f'[stdout]\n{stdout.decode()}')
  if stderr:
    logging.debug(f'[stderr]\n{stderr.decode()}')

def poll(ui, refresh = True):
  ui.notify("polling..")
  import logging

  async def inner():
    await run('tmux wait-for -L p1 \; split-window -d -v -p 20 "/home/gauteh/.bin/met/mail-sync ; tmux wait-for -U p1"')
    await run('tmux wait-for -L p1 \; wait-for -U p1')

    if refresh:
      ui.current_buffer.rebuild()
      ui.update()

  return inner()

def loop_hook(ui):
  return poll(ui, False)
```

but it seems that this will always reset the cursor/buffer, so I could not really get it to work the way I hoped.

**Comment by pazz** [comment]
But the issue with resetting a cursor (I presume you mean urwid focus) is unrelated to the non-existence of async periodic hook calls correct?

**Comment by gauteh** [comment]
Yes, so this pr does not enable my use case anyway.

ons. 6. mai 2020, 11:29 skrev Patrick Totzke <notifications@github.com>:

**Comment by pazz** [comment]
But #1499 might..
I will include your patch for completeness sake.
Thanks

**Comment by gauteh** [comment]
Thanks :)

**Comment by lenormf** [comment]
Could this be a fix for #1478 ?

**Comment by pazz** [comment]
> Could this be a fix for #1478 ?

Yes, thanks for the refedence here @lenormf . It should indeed also allow your construction.

**Pull request merged**
