### PR TITLE
settings: don't fail ugly when section for binding misses

### PR DESCRIPTION
**Pull request by TomasTomecek**
Took me some time to figure out when I started my work on the folder buffer — would like to make it easier for others in future.

### CODE REVIEW

**Comment by pazz** [comment]
i dont understand why you dont just ship an empty section in the default condig as part of the patchset that adds a new buffer?

**Comment by TomasTomecek** [comment]
Well, first you need to know you have to create that section in the default config. I didn't (and was really puzzled by that weirdly looking `KeyError`). I also prefer seeing
```
RuntimeError: "Mode 'my-great-mode' is not in default bindings."
```
rather than
```
KeyError: 'my-great-mode'
```

**Comment by lucc** [comment]
@TomasTomecek sorry to bother you with this old stuff but do you mind rebasing this? And if you remember how the actual problem manifested do you think we can add a test to exercise it? 

As there was no list access with the mode name as a key here previously where did the original KeyError come from?

**Comment by TomasTomecek** [comment]
I'm sorry but I have now idea about this PR any more, hence closing it. Feel free to carry it if you wish.

**Pull request closed without merging**
