### PR TITLE
added hook for the user to sanitize attachments filenames

### PR DESCRIPTION
**Pull request by cinghiopinghio**
the new `hook` name is `attachment_file_name` for the moment.

### CODE REVIEW

**Comment by pazz** [comment]
pushed to testing for now, thx

**Comment by cinghiopinghio** [comment]
Great!
Quoting Patrick Totzke (2015-12-16 16:33:20)

**Comment by pazz** [comment]
i looked it over once more and also pushed to master for the upcoming release :)

**Comment by cinghiopinghio** [comment]
Great news!

Quoting Patrick Totzke (2015-12-16 18:17:27)

**Pull request closed without merging**
