### PR TITLE
[RFC] Fix addressbook completion

### PR DESCRIPTION
**Pull request by lucc**
There are some fine corner cases when generating a TO header from an address book.  Characters like `,'"` might need special treatment.  I opend this PR early (the code is not yet finished) in order to discuss some of the things with you.

Related: #990, #889

Points to check, discuss and decide:
* [x] look up the RFC how To headers have to be formatted
* [ ] write test cases for all corner cases
* [x] decide how we want to treat which special chars in To headers and if we should add quotes in cases where they are not needed, "just to have it look uniform"
* [x] implement our decisions in alot.completion.AbooksCompleter
* [ ] check the test for proper coding style (@dcbaker is this how I should write the tests and the mock stuff?)
* [ ] more tests?
* [ ] you name it …

At the moment I just wrote some tests to show you what I think are the cases we have to take care of.

### CODE REVIEW

**Comment by pazz** [comment]
(I copy my previous comment here so as to close the other issue.)

I have one recipient of the form `"lastname, firstname" <x@y.com>`.  And notmuch address outputs

```
{"name": "lastname, firstname", "address": "x@y.com", "name-addr": "\"lastname, firstname\" <x@y.com>"}
```

Notice the missing quotes in the name part. They should be there, because otherwise the comma will signal the end of the recipient, when using this string as value for the `To` header.

> Maybe we should check that the name does not mess up our To header in general?

yes, I think this should go here:
https://github.com/pazz/alot/blob/master/alot/completion.py#L233
I thought about just quoting the realname bit, so using `\"%s\" <%s>` there.
But actually, what happens if the name contains an odd number of quotes itself?

**Comment by lucc** [comment]
One of the last days I was wondering if our problem was not already solved and really, it is: [email.utils.formataddr()](https://docs.python.org/2/library/email.util.html#email.utils.formataddr). 

I would say that is the correct way to do the quoting (so I checked the point in my initial post, uncheck and comment if you disagree)

**Comment by pazz** [comment]
Great find! So this is a small matter of wrapping this heper function around the the line I linked.
Thanks!

**Comment by lucc** [comment]
I added some commits that should implement this. I also added commits to use email.utils.farmataddr in other places. I wanted to use it in alot/db/utils.py line 411 as well but am not sure about the encode stuff there. So for now I left it. I you can comment on this with more insight I can also use the formataddr there.

I think we don't have to actually look up the RFC any more, I trust python on this, so I checked that item :)

**Comment by pazz** [comment]
OK, let's rename that 'input' variable before pushing to make the codacity bot happy.

**Comment by lucc** [comment]
fixed the comments

**Comment by pazz** [comment]
thanks, LGTM

**Comment by lucc** [comment]
I rebased and removed the `expectedFailure`s.

**Comment by lucc** [comment]
@pazz does this fix #889?

**Comment by pazz** [comment]
yes it does. I'll merge this and close #889 as well. Thanks!

**Pull request merged**
