### PR TITLE
Add vcard addressbook feature.

### PR DESCRIPTION
**Pull request by lucc**
What do you think about this?

Docs are still missing, and one bug has to be fixed (see 1a0fcae, does anybody know how to do this?).

### CODE REVIEW

**Comment by pazz** [comment]
the code looks ok, but i'm not overly exited about introducing another dependency for this..

**Comment by t-8ch** [comment]
I have written a small c program (for speed, python parsing was much to slow) for the same thing:
https://github.com/t-8ch/snippets/blob/master/contactquery.c

**Comment by lucc** [comment]
@t-8ch that looks interesting but how do I compile it? I had no luck with `cc contactquery.c` or `cc -I /usr/include/glib-2 -l glib-2 contactquery.c`. What libraries are needed?

**Comment by t-8ch** [comment]
@lucc there are a README and a Makefile (`make contactquery`) in the repo. If you have problems compiling feel free to open a ticket there.

**Comment by pazz** [comment]
what's the status of this? Do you want to add this to the master branch still? 
If so, you could add some caching method to avoid parsing those files on every call..

**Comment by lucc** [comment]
I did not work on this any more as you said that you don't like the extra dependency. At one point I did try to implement a differnt approach to the addressbook: To have `HookAddressbook` class that would ask a specific user defined hook function for the addresses instead of a specific user defined command. But I never finished and proposed it. I think I decided that it is saver to keep all these things (one can have a similar idea for sending mail) in different processes so exceptions are not tearing down the whole of alot.

(Background: When I first propsed this I had trouble with my addressbook https://github.com/scheibler/khard, because it is pretty slow. So completion was also slow. My idea here was to have some faster vcard parsing code in alot and use khard only to manage the addresses. Now I have written a shellscript/makefile which chaches the addresses and is much faster than khard itself.)

**Comment by pazz** [comment]
OK thanks for the clarification. I'll close this issue for now, we can always reopen it later.

**Pull request closed without merging**
