### PR TITLE
refresh current buffer on SIGUSR1

### PR DESCRIPTION
**Pull request by mpnordland**
Small change to add a signal handler to UI that refreshes the current refreshes the current buffer when the program receives the SIGUSR1 signal. Tested on my system for about a month now and I have seen no problems. This is used to notify alot from my mail downloader to refresh the mail view.

### CODE REVIEW

**Comment by pazz** [comment]
I think this is a great feature. All this PR lacks is some documentation for it :)

**Comment by mpnordland** [comment]
Added documentation to docs/source/usage/synopsis.rst and a docstring to the function

**Comment by lucc** [comment]
About the use case described in the docs: doesn't it make more sense to send the signal from a notmuch hook as you probably run notmuch from offlineimap anyways.

**Comment by mpnordland** [comment]
I hadn't realized notmuch had hooks.

On January 26, 2016 1:24:27 PM EST, Lucas Hoffmann <notifications@github.com> wrote:
>About the use case described in the docs: doesn't it make more sense to
>send the signal from a notmuch hook as you probably run notmuch from
>offlineimap anyways.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pazz/alot/pull/833#issuecomment-175159119

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
