### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by tlevine**
I got as far as I could until getting stuck on this error, in both Python 2.7 and Python 3.4.
```
$ python2.7 -c 'import alot.init as i; i.main()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "alot/init.py", line 12, in <module>
    from alot.db.manager import DBManager
  File "alot/db/__init__.py", line 6, in <module>
    from .thread import Thread
  File "alot/db/thread.py", line 7, in <module>
    from .message import Message
  File "alot/db/message.py", line 8, in <module>
    from notmuch import NullPointerError
  File "/Library/Python/2.7/site-packages/notmuch/__init__.py", line 54, in <module>
    from .database import Database
  File "/Library/Python/2.7/site-packages/notmuch/database.py", line 24, in <module>
    from .globals import (
  File "/Library/Python/2.7/site-packages/notmuch/globals.py", line 27, in <module>
    raise ImportError("Could not find shared 'notmuch' library.")
ImportError: Could not find shared 'notmuch' library.
```

### CODE REVIEW

**Comment by pazz** [comment]
I am fairly sure that the alot docs make it clear that you need both notmuch 
and its python bindings installed. Also, I am not a big fan of pypi
and given that, as you found out, some of alots dependencies are not
available through it, I strongly discourage trying to install alot solely from
pypi (and any hardcoding in order to make this possible).

This said, I welcome work towards a py3k port of course. Have you had a chance
to look through issue #753 ? If so, can you outline how your patches compare
and/or may be integrated into this branch?
Best wishes,
/p


Quoting Thomas Levine (2015-07-19 00:09:22)

**Comment by tlevine** [comment]
I did some of the things mentioned in that patch, but I only fixed
things as they broke. I don't think my patch adds any special support
for PyPI; why do you mention PyPI?

**Comment by lfos** [comment]
Those patches still need a lot of work. Do one thing at a time. Convert *all* the print statements in a single patch, convert *all* the exception handling in a single patch. And don't do two different things within the same patch. Unfortunately, small patches with random chunks from the big "Port to Py3k" patch aren't helpful at all...

Also, I don't think you need to touch the copyright part when making minor changes to the files :)

**Comment by pazz** [comment]
abandoned in favour of #800

**Pull request closed without merging**
