### PR TITLE
envelope: correctly handle folded headers

### PR DESCRIPTION
**Pull request by pacien**
Should fix https://github.com/pazz/alot/issues/1437.

### CODE REVIEW

**Comment by pacien** [comment]
The unit test is nice to have. I don't have any Windows machine to test with CRLF but it should work.

**Comment by pazz** [comment]
in any case, It'd be good to have a test for interpreting multi-line headers as fixed in this PR.

**Comment by pacien** [comment]
I'm confused. There is already a unit test for that included in this PR. Do we need one testing CRLF too? It should work the same as LF is contained in it.

**Comment by pazz** [comment]
Yes, I've overlooked that. cheers.

**Pull request merged**
