### PR TITLE
Clean up old workaround?

### PR DESCRIPTION
**Pull request by pazz**
Should we remove this workaround for [python issue](https://bugs.python.org/issue14983) that was solved upstream?

WARNING: This is a RFC. I have not tested this!

### CODE REVIEW

**Comment by lucc** [comment]
I am in favour of this (compare #1260 :) but we should introduce some tests for this first in order to assure ourselves that we will not break anything.

**Comment by pazz** [comment]
I'm not sure how to test this to be honest. We could add add complicated mime mail, sign it, and verify that some other email client is happy with the format. But that could be a one-off test and need not be part of our test suite.
Having read around a bit in the cited issue for python, it seems that this patch has actually made it into all important stdlib versions in 2014.

**Comment by dcbaker** [comment]
Honestly I think this is fine as-is, we shouldn't be testing that code in another source tree is doing the right think. Hopefully they're testing their own code.

**Comment by lucc** [comment]
@pazz As I am a collaborator on this repo I see the "delete branch" button. I was tempted to click it but first the question: do you want to keep old branches around (there are currently 42 in this repo) or should we delete old branches?

**Comment by pazz** [comment]
not at all, I always forget this. You're welcome to click away old
branches once they are merged :)


Quoting Lucas Hoffmann (2018-08-02 11:31:56)

**Pull request merged**
