### PR TITLE
Remove Java style getters

### PR DESCRIPTION
**Pull request by lucc**
There are some more in the code but I did not know which belong to some urwid interface that we implement and which could be removed.

If you agree I would say we should note which of our methods overwrite/implement some library interface in the docstring of the method. (Another job on the incremental TODO list.)

### CODE REVIEW

**Comment by pazz** [comment]
i like it a lot, this has been bothering my inner pedant for a while now! Is there a standard way to document all properties of a class? I suspect the latter two will not automatically be identified as properties by sphinx because you don't explicitly declare them as such with a decorator?

**Comment by lucc** [comment]
I don't know of a standard way but we can use the class docstring.

**Comment by lucc** [comment]
Should I add a commit to list the exposed variables in the class docstrings?

**Comment by pazz** [comment]
I think that'd be helpful thanks.
Also, If you find other candidates, don't hesitate to mark them in comments as such. I will have a browse through it later regarding urwid interfaces..

**Comment by pazz** [comment]
thanks.

**Comment by lucc** [comment]
I am not sure if it is done. There are still some left but we have to check them against the urdiw interface (and mabe add a comment).

**Pull request merged**
