### PR TITLE
Turn `encrypt_by_default` into a three choice option.

### PR DESCRIPTION
**Pull request by lucc**
See #849 for the initial discussion.

Currently the biggest question seems to be which values we should use for the three choices.  I might add more points for discussion.

This is still WIP.

### CODE REVIEW

**Comment by pazz** [comment]
i directly pushed the docstrings; the second patch is in `testing` and `0.3.8-settings-encrypt-by-default-854` for now. thanks!

**Comment by lucc** [comment]
You should not have pushed that yet! The PR is unfinished, thats why I said it is "WIP = work in progress". I just put it here to be able to discuss it publicly.

Discussion: What do you think about the doc/Makefile commit? Why again are you keeping generated files in git?

**Comment by lucc** [comment]
PS: Ok the docstrings can go to master directly that's no problem but the rest is not ready at all!

**Comment by pazz** [comment]
oh sorry! i thought the 2nd patch actually contained more than the spec change. my bad.
but its only in testing and should not even break any existing configs.

I am not sure i usnerstand the dependency in Makefile patch..

**Comment by lamarpavel** [comment]
Regarding the naming of the option, I think the most transparent would be `encrypt_by_default =` __never__, __always__ or __trusted__.

However, this would break compatibility with the current `True` or `False`. So maybe we can have a transition period where `always` is evaluated the same as `True` and `never` as `False`, so you could say True/False or always/never for the same effect. Then maybe give a warning message upon starting alot that True/False will become deprecated in the future.

**Comment by lucc** [comment]
About the Makefile commit:

It is not necessary for this PR it is just something I noticed when changing the specs. When I updated the spec file and rebuild the html documentation the new text was not in the html file. So I thought that it would be nice to tell the makefile when to rebuild these files automatically. 

About the option change:

1. Are there more (and maybe authoritative from @pazz ?) opinions about the names for the three option values? What about **all**, **none**, **trusted** (or **signed** instead of trusted)?
2. Currently I can not test the code as it is here because of this error:
```
key "encrypt_by_default" in section "accounts, web" failed validation: the value "Valid" is of the wrong type.
```
Where, aside from the spec file, do I need to tell alot that the option can be "Valid"?

**Comment by pazz** [comment]
I have no strong feelings about the naming scheme, but  all/none/trusted sounds about right.
I think it's a good idea to also allow True/False for backwards compatability and interpret them as all/none.

@lucc in the spec file, the line should read


```
 encrypt_by_default = option('all', 'none', 'trusted', 'True', 'False', default='none') 
```

Note the quoted strings for True/False! The values must all be of the same type IIRC.

**Comment by pazz** [comment]
Ah: If you have more unrelated improvements, it'd be best if you put them into a different branch.
I'll cherry-pick the Makefile stuff for instance anyway. Don't worry about this patch, just saying in case you have more :)

**Comment by lucc** [comment]
The problem why I could not test it was just a dangling pip installation of alot that did interfere. This can now be tested by others. 

The "clean up recpient" commit is interesting. I think the last author intended to take only the address (match group 1) because there are parentheses in the regex. It was not a problem with encrypt_by_default=True but with trusted we need it.

**Comment by pazz** [comment]
yes, that looks about right. By the way: the alot-command `encrypt` should now also be able to set one of the three possible values..

**Comment by lucc** [comment]
There is one quirk with the current implementation of `encrypt --trusted` and `toggleencrypt --trusted`. Keys which are already set in the envelope are not checked. So the sequence `encrypt; unencrypt; encrypt --trusted` will sign the message with the same keys as a simple `encrypt`. The reason is that `unencrypt` does not remove the keys from the envelope but simply unsets the encryption bit, or alternatively that `encrypt --trusted` only checks the keys it tries to add and not the ones that are already set in the envelope.
Does this need to be fixed?

Apart from that what do you think about the last commits?

**Comment by pazz** [comment]
Quoting Lucas Hoffmann (2016-03-24 12:38:41)
>    There is one quirk with the current implementation of encrypt --trusted
>    and toggleencrypt --trusted. Keys which are already set in the envelope
>    are not checked. So the sequence encrypt; unencrypt; encrypt --trusted
>    will sign the message with the same keys as a simple encrypt. The reason
>    is that unencrypt does not remove the keys from the envelope but simply
>    unsets the encryption bit, or alternatively that encrypt --trusted only
>    checks the keys it tries to add and not the ones that are already set in
>    the envelope.
>    Does this need to be fixed?


I think you have a good case here.. un[encrypt|sign] should indeed remove the
keys from the envelop.

**Comment by lucc** [comment]
Ok, I will add that soon.

**Comment by lucc** [comment]
I will put the fix for `unsign` in a new PR as this here did not touch the sign topic at all till now.

**Comment by pazz** [comment]
thanks. This patchset looks good to me. I pushed this to branch `0.3.8-settings-encrypt-by-default-854`
and again merged to testing for now.

**Comment by lamarpavel** [comment]
What's the behaviour for recipients with mixed key status? Say there are 3 recipients: A, B and C where A has a trusted key, B has an untrusted key and C has no key.

With `encrypt_by_default = trusted`, this should not encrypt because neither B nor C match the criteria, same for `encrypt_by_default = True`. Currently (in the master branch), alot encrypts the mail with `encrypt_by_default = True` even if one of the recipients (in either `to:` or `cc:`) has no key at all. This results in some people not being able to read the mail at all and I have to manually toggle encryption off in the envelope mode.

I would think that this issue should be addressed by this PR as well, in case it isn't.

**Comment by lucc** [comment]
@lamarpavel check the docs changes in this PR. Currently we behave similar to the old behavioue on master. You are also right about the implications you name (manual toggling etc).

Do you have a suggestion how to handle this scenario differently? Currently I opt for "put the user in control and don't add a gazilion new options to handle every corner case" (as noted elsewhere: https://github.com/pazz/alot/issues/849#issuecomment-191166913)

**Comment by lamarpavel** [comment]
@lucc My proposal would be to introduce no new options. Instead, form a list of all recipients, find the "weakest" one and set it as the bar to be matched against your config.

- If the "weakest" recipient has no public key at all (or none that can be found), then no encryption is applied.
- If the "weakest" recipient has an untrusted key __and__ you set `encrypt_by_default = Trusted`, then no encryption is applied.

Simply define that if any of the recipients does _not_ meet your reguirements, treat all recipients as if they haven't.

Together with issue #849 this would mean that the user is notified, that the outgoing mails are _not_ encrypted (maybe phrase it as "applied encryption does not meet preferred standards") and the user can manually toggle it on.

**Comment by lucc** [comment]
@lamarpavel I like the idea to treat the value of `encrypt_by_default` as a user preferred standard against which the available keys should be checked in a threshold, all-or-nothing like decision.

Not sure how a warning should be displayed. I would not like it to intrusive (like an error message for example) b/c it might often happen that one writes emails to a group of people of whom one knows that one does not have a key for everybody.

**Comment by lucc** [comment]
What do you think @pazz ?

**Comment by lamarpavel** [comment]
@lucc I imagined the warning like a highlight of the "Encrypt" field in envelope mode. Different font color and a text next to it (eg. a unicode symbol of a broken lock, or text such as "encryption preference not met").

**Comment by lucc** [comment]
@lamarpavel sounds good.

@pazz Do you think we/I should add that? To this PR?

**Pull request closed without merging**
