### PR TITLE
Fix hash(TagWidget) with unicode tag representation

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by lucc** [comment]
PS: currently master is totally unusable without this. I can not even view any mail (let alone send some, #1132) because I get this exception *on startup* (the intial `:search`):
```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/luc/vcs/alot/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/luc/vcs/alot/alot/commands/globals.py", line 125, in apply
    sort_order=self.order))
  File "/home/luc/vcs/alot/alot/ui.py", line 375, in buffer_open
    self.buffer_focus(buf)
  File "/home/luc/vcs/alot/alot/ui.py", line 441, in buffer_focus
    posthook(ui=self, dbm=self.dbman, buf=buf, success=success)
  File "/home/luc/.config/alot/hooks.py", line 150, in post_buffer_focus
    fp = buf.body.focus_position
  File "/home/luc/.local/lib/python2.7/site-packages/urwid/listbox.py", line 591, in _get_focus_position
    w, pos = self.body.get_focus()
  File "/home/luc/vcs/alot/alot/walker.py", line 31, in get_focus
    return self._get_at_pos(self.focus)
  File "/home/luc/vcs/alot/alot/walker.py", line 64, in _get_at_pos
    widget = self._get_next_item()
  File "/home/luc/vcs/alot/alot/walker.py", line 77, in _get_next_item
    next_widget = self.containerclass(next_obj, **self.kwargs)
  File "/home/luc/vcs/alot/alot/widgets/search.py", line 28, in __init__
    self.rebuild()
  File "/home/luc/vcs/alot/alot/widgets/search.py", line 148, in rebuild
    minw, maxw, align_mode)
  File "/home/luc/vcs/alot/alot/widgets/search.py", line 119, in _build_part
    for t in self.thread.get_tags())
  File "/home/luc/vcs/alot/alot/widgets/search.py", line 119, in <genexpr>
    for t in self.thread.get_tags())
  File "/home/luc/vcs/alot/alot/widgets/globals.py", line 293, in __init__
    self.__hash = hash('{}_{}'.format(self.translated, self.txt))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u2197' in position 0: ordinal not in range(128)
```

**Comment by ibotty** [comment]
I also ran into that bug and the proposed fix correctly fixes it.

**Comment by pazz** [comment]
I can also confirm this bug.

**Comment by dcbaker** [comment]
Sorry about that. I should have realized that unicode would break here.

**Pull request merged**
