### PR TITLE
Don't use __str__ of  error BadSignature

### PR DESCRIPTION
**Pull request by mschaaf**
It seems not to be to handle error messages of different locale than en
this fixes issue #1161

### CODE REVIEW

**Comment by dcbaker** [comment]
does using unicode instead of str work? I'd really like to not reimplement the error message handling of gpg. If using unicode doesn't work, then we probably need to do some encode/decode magic.

**Comment by mschaaf** [comment]
unicode didn't work. IMHO, doing some "encode/decode magic" in alot does not work because the exception is thrown in the gpgme code and not alot.

**Comment by dcbaker** [comment]
more python2 bonghits. I'm sure this works correctly in python3.

Could you change the name of the function to follow PEP8 convention? (all lower case with _ separators) and add a comment to the function explaining that this is a workaround for gpg not handling non-ascii data correctly, and that it may not be necessary for python 3? I'd be willing to merge it with those changes.

**Comment by mschaaf** [comment]
@dcbaker Thanks for your comments. I applied them.

**Comment by pazz** [comment]
I'm late to the party so excuse my silly question here: It seems that you do decoding voodoo basically to properly pass on an error message for a very specific error.
Why not hardcode an appropriate message instead?

**Comment by mschaaf** [comment]
It is now partly hardcoded and the other part is the fingerprint for the bad signature.

**Comment by mschaaf** [comment]
@dcbaker and @pazz What is missing to get this merged?

**Comment by pazz** [comment]
@dcbaker So if I understand correctly, this is a hotfix for python2 that will eventually be removed due to proper unicode handling in python3 yes?

@mschaaf thanks for the changes and sorry for the delay. If you could just squash these two commits into one I'd be happy to merge this. (I know I'm being pedantic but I'm trying to avoid commits that are introducing code that is imediatedly removed/superseded). Thanks!

**Comment by dcbaker** [comment]
@pazz I think so. IIRC gpgme uses unicode strings in python 3, but bytestrings in python 2. Thus things like this.

**Comment by pazz** [comment]
ok great. so I'll just push the squashed version of this then.

**Comment by mschaaf** [comment]
@pazz Ready to merge.

**Comment by pazz** [comment]
cool, thx

**Pull request merged**
