### PR TITLE
Fix async idle

### PR DESCRIPTION
**Pull request by dcbaker**
It turns out that urwid just doesn't work very will with asyncio. I simply don't have time or motivation to try to fix urwid, so instead I'm proposing trying to get the nice syntax of asyncio, but without the overhead by continuing to use urwid's `TwistedEventLoop`. Since we've installed the twisted reactor as the asyncio loop, starting Twisted's loop starts processing asyncio calls.

### CODE REVIEW

**Comment by dcbaker** [comment]
stupid codeclimate, it's mad that an inline comment goes slightly past 79 characters.

**Comment by pazz** [comment]
thanks for taking the time @dcbaker !
Did you poke the urwid devs about this as well?
Should we somewhere document, or at least add a note-to-self, that we'd like to eventually switch to urwids asyncio eventloop?

**Comment by dcbaker** [comment]
I think it would be nice to use the asyncio loop, but that would require urwid fixes, so I don't know if that will happen.

**Comment by pazz** [comment]
understood, thx!

**Pull request merged**
