### PR TITLE
Replace twisted with asyncio

### PR DESCRIPTION
**Pull request by dcbaker**
I got a bit of free time, and sat down to work on something I'd really wanted to work on since we started the transition to python 3, using asyncio.

I think there are some benefits for us to using asyncio instead of twisted. Asyncio is part of the language, and it gives us nice language features like `async def` and `await`. On the downside it doesn't have as many nice convenience functions as twisted does. It also removes a pretty big, heavy dependency. Twisted is pretty cool, and you can do a lot of cool stuff with it, but we're basically just using the event loop and deferreds.

This series has been lightly tested, it does pass all of the unittests, although there are some obvious holes in the coverage of our test suite :/. I'm currently dog fooding it, but if anyone sees obvious mistakes or problems I'd be glad to start working through them sooner than later (as time at $job and $life allows).

### CODE REVIEW

**Comment by pazz** [comment]
When I try to respond to an email with this, my editor is not spawned as usual and instead the terminal window is just blank. I have both `editor_spawn`, and `editor_in_thread` undefined in the config, which means they default to false. See the log below.

```
DEBUG:globals:No encryption by default, encrypt_by_default=none
INFO:envelope:editable headers: {'Subject'}
DEBUG:globals:using editor_cmd: vim -c "set spell"
DEBUG:globals:{'spawn: ': False, 'in_thread': False}
DEBUG:globals:{'spawn': False}
DEBUG:globals:cmdlist: ['vim', '-c', 'set spell', '/tmp/alot.u8kl93ug.eml']
INFO:globals:calling external command: ['vim', '-c', 'set spell', '/tmp/alot.u8kl93ug.eml']

```

**Comment by dcbaker** [comment]
Okay, I've addressed the editor thing, it has to do with using the `helper.call_cmd`; since that's kinda orthogonal to the point of this merge request I've dropped those patches. I've also fixed a few sending bugs I ran into. I'll see what I can do about making pep8 happy.

**Comment by dcbaker** [comment]
Okay, I've fixed all but one of the pep8 issues, the one left is pretty silly it's an 81 character line, and the last three characters are `)`, I think a newline hurts the readability rather than helping. The other issues are me adding fixme comments.

**Comment by dcbaker** [comment]
And I've fixed a whitespace error I introduced in my fixups...

**Comment by pazz** [comment]
question: do you intent to fix the Todo/xxx/fixme's as part of this series?

**Comment by dcbaker** [comment]
no. I think all of those are worth fixing, but they're not related to the twisted -> asyncio transition. I have some patches for some of those I'm planning to submit if/when this lands.

**Comment by pazz** [comment]
Thanks, that makes sense as this series is large enough as it is. I'll ok the failing codeclimate check.  @lucc: let's testrun this for a few days..

**Comment by lucc** [comment]
I already started using it.  The first thing I noticed was the delay on startup.  My initial command opens three buffers and then switches to the first one (and pops up a notification). I can see all the buffers flicker by for a sort moment.  That's not really a problem, only a glitch but it wasn't there with the old implementation.

Ref:
```
initial_command = bufferlist; search query:inbox; search query:listbox; buffer 0; call hooks.version_notification(ui)
```

**Comment by dcbaker** [comment]
I see the same thing in my setup. I'm not exactly sure why we have that, I don't know if twisted wasn't actually deferring while running the initial command line, or if it was faster.

**Comment by lucc** [comment]
If alot is already running and I do `:search foo ; search bar` it opens both buffers after another on either branch.

**Comment by dcbaker** [comment]
And the raises directive isn't correct either :)

**Comment by dcbaker** [comment]
Sure.

**Comment by pazz** [comment]
It seems that on this branch, calls to external programs that write to stderr result in error notifications in alot. I noticed that when I opened a PDF attachment. This opens my viewer (zathura) as expected. But when I close it again and alot resumes, I get the error notifications.

**Comment by dcbaker** [comment]
- Fixed typo and a couple other sphinx syntax issues
- replace uses of `asyncio.ensure_future` with `loop.create_task`, which is recommended by python upstream

**Comment by dcbaker** [comment]
Fixed the errors after running external commands, also fixed shell calls in external command

**Comment by pazz** [comment]
@dcbaker: can I ask you to go through recent PRs that are ready and merge them, then rebase this branch? I think this is ready to go but I want to avoid having to rebase many other PRs as a result of just merging this one..

**Pull request merged**
