### PR TITLE
Spam-marking command

### PR DESCRIPTION
**Pull request by FiskerLars**
I have been increasingly been taken aback from the amount of steps I had to undertake to feed manually tagged spam to feeding my bayesian classifier (spamassassin here). Maybe I got it wrong, but 

1. labelling a thread as spam (7 keypresses)
2. opening up a shell and feeding all recently spam-marked emails to the classifier
3. removing all spam from the inbox

is way to complicated for a daily task.

Thus, I wanted something like 'S' to do all of this for me and created a command with a neat hook. (Plus, further down the line, I had to make the sendmail-send-command synchronous, as I ran into what seems to me like a racing condition for slower sendmails, i.e. /dev/stdin is closed or not opened when sendmail requires the data, leading to a failure.)

Hope this seems useful for you as well. Thanks for the great email client, it is helping me with my communication a lot ;-)

### CODE REVIEW

**Comment by lucc** [comment]
Hello @FiskerLars nice that you want to contribute. As it stands it is not clear why alot can not yet do the things you want to do. You know that you can bind longer command sequences and hooks to a single key press?

For the sync/async problem: Can you provide a test case that excises the problem? We are hoping to block the user interface as little as possible so making something explicitly synchronous needs a good justification.

For new features like commands or options: You should definitely provide documentation for those. Otherwise you are the only one who knows how to use it and then all you efforts for the community are in vain. If possible you should also provide tests.

**Comment by pazz** [comment]
is the sendmail thing related to #1372?

I agree that the spam-marking stuff should go into a custom hook and with some documentation also into our [wiki](https://github.com/pazz/alot/wiki/Contrib-Hooks).  Thanks

**Comment by FiskerLars** [comment]
Hi,
sorry for not checking the issue-list beforehand and for having to unrelated patches in one pull request.

The race condition occurs (probably in my specific case) within a wrapper script around esmtp. In order to queue a mail some file-system-action occurs before stdin is read. I can only assume that the pipe is teared down before the read happens. 

For clarification, the read happens very much to the end. At that point stdin is empty. The problem strangely only occurred after this script had been used for well over a year:

`queue_mail() { # ($@)
    local ret=0
    mkdir -p "$qdir" || {
        echo "unable to create queue dir $qdir" 2>&1
        return 1
    }
    mdir="`$mktemp -d "$qdir/XXXXXXXX"`"
    [ -d "$mdir" ] || {
        echo "unable to create tempdir inside $qdir" 2>&1
        return 1
    }
    touch "$mdir/lock"
    echo "$@" >"$mdir/cmd" || ret=1
    cat </dev/stdin >"$mdir/mail" || ret=1
    [ $ret -eq 0 ] || {
        echo "could not enqueue mail in dir $mdir" 2>&1
        return 1
    }
`

Writing on this topic, I could try to have the read from stdin earlier in the code and try that

**Comment by lucc** [comment]
I took the liberty to put block code markers around your code. But it looks fragmented and the braces don't match. Is that the full script you are using? What interpreter is it using? What does it do?

**Comment by pazz** [comment]
I'm closing this because just like @lucc I think this feature should not be part of mainline alot.
Instead, manual spam-marking should for now be done in custom hooks (which you can bind to keys if you like via the `call` command). You may also want to have a look at [afew](https://github.com/afewmail/afew).

Finally, next time you send a PR, please don't mix in a `fix` for the unrelated sendmail issue and open a separate issue instead. Cheers!

**Pull request closed without merging**
