### PR TITLE
marking and unmarking of spam threads in search mode in a single command

### PR DESCRIPTION
**Pull request by FiskerLars**
I assign them to S and H keys respectively, by default.

Adding a spam learning hook is still TODO

### CODE REVIEW

**Comment by lucc** [comment]
I do not really understand why there needs to be an extra command for this and why it needs to go into alot. Why can it not be a binding or a hook in your config?

**Comment by FiskerLars** [comment]
OK, I try to handle it as a hook/binding somewhere

**Comment by lucc** [comment]
I am mostly asking *why*! If there is a good reason to do it in alot and not in a hook we can discuss it.  At the moment it just looks like a binding to tag/untag with `spam,killed`. If that is everything it is better done in the users config. If there is some special hook logic that can not be done with a `:call` and is beneficial to other users it has a chance of being merged.

**Comment by lucc** [comment]
If you have an interesting hook or so you can also contribute it to the wiki.

**Pull request closed without merging**
