### PR TITLE
Add signal for SIGINT callback ExitCommand

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Hello,
this patch bind the SIGINT (C-c) signal to an exit command, 
that way is you configure the 'bug_on_exit' flag you can confirm before quitting,
if you don't you still get a cleaner way for quitting due to the ExitCommand().

### CODE REVIEW

**Comment by pazz** [comment]
This looks nice!
The logging should rather say something like "shut down cleanly", but apart from that I'm happy.
I just skimmed the `exit` code and I cannot see how the case is dealt with, when the `dbman.writequeue` is not empty (because some flush failed due to a locked notmuch index).
In that case, `exit` should warn/wait/retry `dbman.flush()`.

**Comment by GuillaumeSeren** [comment]
@pazz 
Ok I have upgrade the log message.
I feel a bit the same about the exit code, I mean I am not sure it cover every case possible.
It check the ui.db_was_locked, so maybe we can call the FlushCommand instead of (hard) checking db_was_locked, that way if the flush is not complete we can stop the quit.

This have the advantage of beeing good for all exit case IMO.

**Comment by pazz** [comment]
did you forget to push the amended patch?
sidenote: i think it'd be nicer to check the signal for equality with `signal.SIGINT`, not just 2..

**Comment by GuillaumeSeren** [comment]
No I was trying to find something better for the 'dbman.writequeue' check.

**Comment by GuillaumeSeren** [comment]
From my understanding, the patches do the job described in the issue #851 
I feel that the flag db_was_locked populated by the FlushCommand, can be good enough,
and if we need a better check, it may be simpler to upgrade FlushCommand directly.

Are you agree ?

**Comment by pazz** [comment]
yes. i will push this patch as it is. thank you.
we should open a new issue for this flushing stuff

**Comment by GuillaumeSeren** [comment]
Great ! :beers:

**Pull request merged**
