### PR TITLE
travis: generate coverage report

### PR DESCRIPTION
**Pull request by lucc**
Generate a coverage report and upload it to codacy.com as discussed in #1087.

@pazz as said in https://github.com/pazz/alot/issues/1087#issuecomment-320333120 I will need your help to generate and encrypt an API token for codacy.  You could post the encrypted token as a comment in this PR, then I will amend my commit.  You could also try to run these commands on the command line first to see if it works:
```sh
pip2 install --user coverage codacy-coverage
coverage run setup.py test
coverage xml
export CODACY_PROJECT_TOKEN='the unencrypted token'
codacy-coverage -r coverage.xml
```

### CODE REVIEW

**Comment by pazz** [comment]
I get this:

```
 coverage run setup.py test                                                                      ✭master 
/usr/lib/python3/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.6.0dev' to '0.6.0.dev0'
  normalized_version,
running test
Searching for pygpgme>=0.2
Reading https://pypi.python.org/simple/pygpgme/
Downloading https://pypi.python.org/packages/dc/96/b2bcbd3a216af313bb9045c2e573aa18653876a65db471b86be7598234dd/pygpgme-0.3.tar.gz#md5=d38355af73f0352cde3d410b25f34fd0
Best match: pygpgme 0.3
Processing pygpgme-0.3.tar.gz
Writing /tmp/easy_install-pp4v40kc/pygpgme-0.3/setup.cfg
Running pygpgme-0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pp4v40kc/pygpgme-0.3/egg-dist-tmp-lg7i13ui
In file included from src/gpgme.c:22:0:
src/pygpgme.h:24:19: fatal error: gpgme.h: No such file or directory
 #include <gpgme.h>
                   ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

in step 2 but I think this might be a local issue..
I'll post the api token here in good faith, assuming that it will be public anyway as it will show in our travis config file in plain text..

```
CODACY_PROJECT_TOKEN='df4443e7313e4ae599bcbbaf4835b00f'
```

cheers,
P

**Comment by lucc** [comment]
Thank you @pazz. Travis said that the upload was successful: https://travis-ci.org/pazz/alot/jobs/261294642

**Comment by pazz** [comment]
maybe they only keep track of the master branch? I'd be happy to give it a go and merge this

**Comment by pazz** [comment]
seems to work :-)

**Pull request merged**
